---

- name: Copy rabbitmq.conf file
  ansible.builtin.copy:
    src: rabbitmq.conf
    dest: /opt/backend/rabbitmq.conf

- name: Copy docker-compose file
  ansible.builtin.copy:
    src: backend-compose.yml
    dest: /opt/backend/docker-compose.yml

- name: Create .env file
  ansible.builtin.template:
    src: env.conf.j2
    dest: /opt/backend/.env

- name: Pull images
  community.docker.docker_compose_v2_pull:
    project_src: /opt/backend

# Elastic can be very very slow to start
- name: Start slow backend dockers
  community.docker.docker_compose_v2:
    project_src: /opt/backend 
    wait: true
    wait_timeout: 180
