---

- name: Copy docker-compose file
  ansible.builtin.copy:
    src: opencti-compose.yml
    dest: /opt/opencti/docker-compose.yml

- name: Create .env file
  ansible.builtin.template:
    src: env.conf.j2
    dest: /opt/opencti/.env

- name: Pull images
  community.docker.docker_compose_v2_pull:
    project_src: /opt/opencti

- name: Start OpenCTI docker
  community.docker.docker_compose_v2:
    project_src: /opt/opencti
    state: present
    wait: true
    wait_timeout: 180

- name: Wait until OpenCTI HTTP status is 200
  uri:
    url: 'http://localhost:8080/'
    return_content: yes
    validate_certs: no
    status_code:
      - 200
  until: uri_output.status == 200
  retries: 24
  delay: 5
  register: uri_output
