---

- name: Copy OpenBAS docker-compose file
  ansible.builtin.copy:
    src: openbas-compose.yml
    dest: /opt/openbas/docker-compose.yml

- name: Create .env file
  ansible.builtin.template:
    src: env.conf.j2
    dest: /opt/openbas/.env

- name: Pull OpenBAS images
  community.docker.docker_compose_v2_pull:
    project_src: /opt/openbas

- name: Start OpenBAS docker
  community.docker.docker_compose_v2:
    project_src: /opt/openbas
    state: present
    wait: true
    wait_timeout: 180

- name: Wait until OpenBAS HTTP status is 200
  uri:
    url: 'http://localhost:8081/'
    return_content: yes
    validate_certs: no
    status_code:
      - 200
  until: uri_output.status == 200
  retries: 24
  delay: 5
  register: uri_output
