---

- name: Create internal-import-file connectors
  ansible.builtin.unarchive:
    src: connectors.tgz
    dest: /opt/connectors

- name: Start internal-import-file docker
  community.docker.docker_compose_v2:
    project_src: "/opt/connectors/internal-import-file/{{ item }}/"
    state: present
    wait: true
    wait_timeout: 180
  loop: ludus_filigran_opencti_internal-import-file 