---

- name: Set vm.max_map_count for elasticsearch
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: '1048575'
    state: present

- name: Create opencti folder
  ansible.builtin.file:
    path: /opt/opencti
    state: directory
    mode: '0755'

# TODO update to new version
# stop old docker but keep volume

- name: Copy docker-compose file
  ansible.builtin.copy:
    src: "{{item}}"
    dest: "/opt/opencti/{{item}}"
  loop:
    - docker-compose.yml
    - rabbitmq.conf

- name: Create .env file
  ansible.builtin.template:
    src: env.conf.j2
    dest: /opt/opencti/.env

- name: Pull images
  community.docker.docker_compose_v2_pull:
    project_src: /opt/opencti

# Elastic can be very very slow to start
- name: Start slow depends_on dockers
  community.docker.docker_compose_v2:
    project_src: /opt/opencti 
    services : 
      - redis
      - elasticsearch
      - minio
      - rabbitmq
      - pgsql
    wait: true
    wait_timeout: 180

- name: Start OpenCTI docker
  community.docker.docker_compose_v2:
    project_src: /opt/opencti 
    state: present
    services:
      - opencti
      - worker
    wait: true
    wait_timeout: 180

- name: Wait until OpenCTI HTTP status is 200
  uri:
    url: 'http://localhost:8080/'
    return_content: yes
    validate_certs: no
    status_code:
      - 200
  until: uri_output.status == 200
  retries: 24
  delay: 5
  register: uri_output

- name: Start OpenBAS docker
  community.docker.docker_compose_v2:
    project_src: /opt/opencti 
    state: present
    services : openbas
    wait: true
    wait_timeout: 180

- name: Wait until OpenBAS HTTP status is 200
  uri:
    url: 'http://localhost:8081/'
    return_content: yes
    validate_certs: no
    status_code:
      - 200
  until: uri_output.status == 200
  retries: 24
  delay: 5
  register: uri_output

- name: Start the connectors
  community.docker.docker_compose_v2:
    project_src: /opt/opencti 
    services : 
      - connector-export-file-stix
      - connector-export-file-csv
      - connector-export-file-txt
      - connector-import-file-stix
      - connector-import-document
      - connector-analysis
      - connector-cisa-known-exploited-vulnerabilities
      - connector-mitre
      - collector-mitre-attack
      - collector-atomic-red-team
    wait: true
    wait_timeout: 120

- name: Touch the .finish file
  ansible.builtin.file:
    path: "/opt/opencti/opencti_{{ ludus_filigran_opencti_version }}.finish"
    state: touch