---

- name: Check Docker
  block:
    - name: Get info on docker host
      community.docker.docker_host_info:
      register: result
    - name: Print a message
      ansible.builtin.debug:
        msg: 'docker is fine'
  rescue:
    - name: Install Docker on Ubuntu
      ansible.builtin.include_tasks:
        file: docker_ubuntu.yml
      when: ansible_distribution == 'Ubuntu'
    - name: Install Docker on Debian 
      ansible.builtin.include_tasks:
        file: docker_debian.yml
      when: ansible_distribution == 'Debian'


- name: Check that /opt/opencti/opencti6.5.9.finish exists
  stat:
    path: /opt/opencti/opencti6.5.9.finish
  register: opencti_result

- name: Install OpenCTI
  ansible.builtin.include_tasks:
    file: install_opencti.yml
  when: not opencti_result.stat.exists

